INSERT INTO "CuentasContables" ("Id", "Codigo", "Nombre", "Tipo", "Activo", "FechaCreacion")
VALUES
    (gen_random_uuid(), '5397050102', 'HORAS EXTRAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397050204', 'BONIFICACION ADMINISTRATIVA V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397050205', 'BONIFICACION NO PRESTACIONAL V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397050206', 'BONIFICACION PRESTACIONAL V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397050302', 'NOMINAS Y LIQUIDACIONES X COB V-T INFOR', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397050402', 'COMISIONES V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397053002', 'CESANTIAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397053302', 'INTERESES SOBRE CESANTIAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397053602', 'PRIMAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397053902', 'VACACIONES V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397100102', 'HONORARIOS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397350101', 'SERVICIOS PUBLICOS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397350104', 'SEGURO BOLIVAR AGROPEC V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397350105', 'SERVICIO ASEO V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397350106', 'POLICIAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397450102', 'MANTENIMIENTO V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950110', 'OBSEQUIOS INTERNOS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950111', 'DATAFONOS DOBLES V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950114', 'BOTIQUIN V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950120', 'SEG SOC GILBERTO OFICINA PRINCIPAL V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950121', 'TRANSPORTES V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950122', 'DESCUADRES EN CAJA V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950123', 'SOBRANTE CAJERA V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950124', 'ABONO ENTRE PUNTOS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950125', 'GASTOS CRED A OTRAS EMPRESAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950126', 'PAGO FACTURAS A OTRAS EMPRESAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950127', 'COMPRAS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950128', 'CASINO Y RESTAURANTE V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950129', 'PAPELERIA V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950130', 'AVISO Y PUBLICIDAD V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950131', 'GASTOS V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950132', 'CAMBIO MENUDO AGROPORCICOLA V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950133', 'GASTOS PERSONALES GILBERTO SERRA PDV V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950503', 'PRESTAMOS CRISTIAN Y GILBERTO V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950504', 'GASTOS PERSONALES GILBERTO OFIC V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950505', 'ABONOS DE MAS EN PAGOS DE CLIENTES V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950506', 'NOMINA CUOT ADMINIST OFIC X COBRAR V-T', 'GASTO', true, CURRENT_TIMESTAMP),
    (gen_random_uuid(), '5397950510', 'TRAMITES Y LICENCIAS V-T', 'GASTO', true, CURRENT_TIMESTAMP)
ON CONFLICT ("Codigo") DO NOTHING;
