ALTER TABLE "Impuestos"
ALTER COLUMN "CuentasBase" TYPE BOOLEAN
  USING CASE WHEN NULLIF(BTRIM("CuentasBase"), '') IS NULL THEN FALSE ELSE TRUE END,
ALTER COLUMN "CuentasBase" SET DEFAULT FALSE,
ALTER COLUMN "CuentasBase" SET NOT NULL,
ALTER COLUMN "CuentasBaseDevoluciones" TYPE BOOLEAN
  USING CASE WHEN NULLIF(BTRIM("CuentasBaseDevoluciones"), '') IS NULL THEN FALSE ELSE TRUE END,
ALTER COLUMN "CuentasBaseDevoluciones" SET DEFAULT FALSE,
ALTER COLUMN "CuentasBaseDevoluciones" SET NOT NULL;